Vagrant.configure("2") do |config|

  config.vm.box = "gbailey/amzn2"
  config.vm.synced_folder "../../", "/usr/share/nginx/html/"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
    vb.name = "vagrant_oneapp"
  end

  config.vm.provision "shell", path: './box_files/dependencias.sh'
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "private_network", ip: "192.168.50.11"
  config.ssh.extra_args = ["-t", "cd /usr/share/nginx/html/; bash --login"]

end
