version: '3'
services:
  db_bo:
    container_name: oneapp_bo_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: oneapp_bo
    volumes:
      - oneapp_bo:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      bo_net:
        ipv4_address: 192.168.50.12
    working_dir: /var/lib
  oneapp_bo:
    container_name: oneapp_bo_project
    depends_on:
      - db_bo
    volumes:
      - ../../:/usr/share/nginx/html
    image: oneapp_bo_project
    build:
      context: ./image_files/
      args:
        - PHP_VERSION
    privileged: true
    working_dir: /usr/share/nginx/html
    networks:
      bo_net:
        ipv4_address: 192.168.50.11
    command: /usr/sbin/init && systemctl restart php-fpm.service && systemctl restart nginx.service
networks:
  bo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/16
          gateway: 192.168.50.1

volumes:
  oneapp_bo:
