version: '3'
services:
  db_bo:
    container_name: oneapp_bo_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: oneapp_bo
    volumes:
      - oneapp_bo:/var/lib/mysql
    ports:
      - "3307:3306"
    working_dir: /var/lib
  oneapp_bo:
    container_name: oneapp_bo_project
    depends_on:
      - db_bo
    volumes:
      - ../../:/usr/share/nginx/html
    image: oneapp_bo_project
    build: ./image_files/
    privileged: true
    working_dir: /usr/share/nginx/html
    ports:
      - "8081:80"
    command: /usr/sbin/init && systemctl restart php-fpm.service && systemctl restart nginx.service
volumes:
  oneapp_bo:
